source 'https://rubygems.org'


gem 'rails', '4.2.0'

gem 'rails-api'

gem 'spring', :group => :development


gem 'sqlite3'

gem 'ruby-opencv'
gem 'tesseract-ocr'
gem 'ots'
gem 'gingerice'
gem 'rest-client'
gem 'sentimental'
